const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["早睡早起真的有科学依据：身体有自己的钟","晚上11点到凌晨3点是深度睡眠黄金期肝胆排毒时间。长期熬夜增加心血管疾病和糖尿病风险。","睡眠养生"],["中医说的湿气是什么：怎么判断自己湿气重","舌苔厚腻有齿痕、大便黏马桶不成形、身体沉重不想动、面部和头发容易出油。薏米红豆水祛湿效果好。","中医养生"],["冬季泡脚的5个好处：怎么泡效果最好","水温40-45度别太烫、时间20-30分钟微微出汗即可、水位要没过脚踝最好到小腿。加点艾草或生姜驱寒效果更好。","养生习惯"]],[["气血不足怎么补：食补比药补更安全","红枣枸杞桂圆当归补血、黄芪党参补气。红色和黑色食物大多补血（红枣黑芝麻黑豆红糖）。先调理脾胃吸收才好。","食疗养生"],["颈椎不舒服怎么办：5个动作缓解颈椎病","米字操每天做3次、靠墙站立收下巴、颈椎对抗训练。调整电脑屏幕高度与视线平行是最有效的预防。","养生动作"],["失眠吃什么：10种助眠食物","香蕉富含镁放松肌肉、温牛奶含色氨酸促进褪黑素分泌、核桃樱桃奇异果也有助眠效果。","睡眠养生"]],[["泡脚有什么好处：不只是一盆热水","促进血液循环改善手脚冰凉、缓解疲劳帮助入睡、驱寒祛湿、调理月经。但静脉曲张和糖尿病足慎泡。","养生习惯"],["枸杞的正确吃法：直接嚼还是泡水","干嚼最好吸收营养不浪费（每天10-20粒）。泡水的水温不要超过60度维C怕高温。泡到变白就吃掉。","食疗养生"],["口干口苦口臭是怎么回事：可能是内脏信号","口苦可能是肝胆有问题、口臭可能是胃不好或口腔细菌、口干可能是阴虚。夜间严重建议看中医调理。","常见问题"]],[["每天梳头100下有什么好处","刺激头部血液循环促进头发生长、缓解头痛和压力、改善睡眠。用木梳或牛角梳不要塑料梳。","养生动作"],["艾灸入门：常用穴位和艾灸注意事项","足三里健脾胃、关元补元气、三阴交调妇科。每次15-20分钟、隔天一次、灸后不要马上洗澡碰冷水。","中医养生"],["为什么总感觉很累：可能是慢性疲劳的表现","排除甲状腺问题和贫血后看看生活习惯：睡眠不足、压力过大、缺乏运动、饮食不均衡都可能导致。","常见问题"]],[["黑芝麻的养生功效和吃法","补肝肾乌发明目润肠。炒熟捣碎吸收最好、可以拌饭拌粥、做黑芝麻糊。每天一勺就够热量不低。","食疗养生"],["穴位按摩入门：6个重要的保健穴位","百会穴在头顶正中提神醒脑、合谷穴在手背虎口止痛、内关穴在手腕内侧缓解心慌恶心、太冲穴在脚背疏肝理气。","穴位养生"],["空调病怎么预防：夏天也记得出出汗","空调温度不低于26度、不要直对着吹、每2小时开窗通风、加湿器保持湿度。夏天出出汗对身体有好处。","养生习惯"]],[["红糖红枣枸杞水：女生必备养生茶","经期前后喝暖宫补血、日常喝改善手脚冰凉。红糖选古法红糖不要赤砂糖。枸杞选宁夏枸杞不是新疆大枸杞。","食疗养生"],["经常上火是什么原因：实火和虚火的区别","实火=口干口苦面红长痘用清热药、虚火=手心热失眠盗汗用滋阴药。吃生冷降实火吃温补降虚火方向完全不同。","中医养生"],["冥想入门：每天10分钟减轻焦虑","不需要盘腿坐椅子上也可以。专注呼吸每次呼气默数1到10。走神了没关系温柔地把注意力拉回来。","养生心理"]],[["春天养生重点：养肝护肝","春季对应肝脏。多吃绿色蔬菜少吃油腻、保持心情舒畅不生气、早睡早起、适当运动。菊花决明子茶清肝明目。","四季养生"],["夏天养生重点：养心静心","夏季对应心脏。午睡20-30分钟补心气、多吃红色食物（西瓜红豆番茄）、喝绿豆汤解暑、不要贪凉。","四季养生"],["秋天养生重点：养肺润肺","秋季对应肺部。多吃白色食物（梨百合银耳山药）、多喝水防秋燥、秋季是排毒黄金季。","四季养生"]],[["冬天养生重点：养肾藏精","冬季对应肾脏。早睡晚起跟着太阳的节奏、多吃黑色食物入肾（黑豆黑芝麻黑米）、注意保暖腰部。","四季养生"],["八段锦入门：8个简单动作强身健体","两手托天理三焦、左右开弓似射雕、调理脾胃须单举、五劳七伤往后瞧。每天15分钟效果不比跑步差。","养生动作"],["养生不是中老年人的专利：30岁就该注意了","30岁开始基础代谢每10年下降5%。现在养的好以后花在看病上的时间和钱就少。养生是长期投资。","养生观念"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0][2]+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#65a30d;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('OK');
